management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 9092
#spring:
#  cloud:
#    stream:
#      kafka:
#        binder:
#          zkNodes: localhost:2181
#          brokers: localhost:9092
#          autoAddPartitions: true